# In your pyproject.toml file

[project]
name = "voxcmd"
version = "1.2.0" # or whatever your version is
dependencies = [
    "typer[all]",
    "google-genai",
    "rich",
    # click and python-dotenv can be removed
]

# 👇 THIS IS THE LINE TO CHANGE 👇
[project.scripts]
voxcmd = "voxcmd:app" 